### ISSUE TITLE
 the amuleweb binary cannot be run

### ISSUE THREAD

**Issue by Anyfc** [openwrt-stuff/openwrt-extra#3]
自编译的网件4300 lede master源码固件，安装的是
你编译好的包：
http://pan.baidu.com/s/1jIK18Xo

在安装完后第一次启动时，在luci那里 amuleweb 选项 出现了一下就消失，再次运行提示：

ERROR You requested to run web server on startup, but the amuleweb binary cannot be run. Please install the package containing aMule web server, or compile aMule using --enable-webserver and run make install

但是用 aMuleGUI 是可以远程连接到路由上的amule并进行下载的，请问这个是什么原因造成的。

**Comment by maz-1** [comment]
这个问题和这个repo无关，Makefile是正确的，可以自己编译。
